[de MODULE_INFO
  ("name"       "jidoteki-admin-api")
  ("version"    "1.22.0")
  ("summary"    "On-Prem Admin API")
  ("source"     "https://jidoteki.com")
  ("author"     "Alexander Williams")
  ("license"    "MPL-2.0")
  ("copyright"  "(c) 2015-2018 Alexander Williams, Unscramble <license@unscramble.jp>")
  ("install"    "make")
  ("requires"
    ("jidoteki-admin"    "v1.22.0"    "https://github.com/on-prem/jidoteki-admin.git") ]
