[de MODULE_INFO
  ("name"       "jidoteki-admin-api")
  ("version"    "1.18.1")
  ("summary"    "Jidoteki Admin API")
  ("source"     "https://jidoteki.com")
  ("author"     "Alexander Williams")
  ("license"    "MPL-2.0")
  ("copyright"  "(c) 2015-2017 Alexander Williams, Unscramble <license@unscramble.jp>")
  ("install"    "make")
  ("requires"
    ("picolisp-unit"    "v2.1.0"    "https://github.com/aw/picolisp-unit.git")
    ("picolisp-json"    "v2.2.0"    "https://github.com/aw/picolisp-json.git")
    ("picolisp-semver"  "v0.9.0"    "https://github.com/aw/picolisp-semver.git") ]
